### PR TITLE
Adding JEC for Run3 and apply JES on data

### PR DESCRIPTION
**Pull request by valsdav**
For Run3 datasets, we need to apply jet energy scale corrections also on nominal MC and on Data. 

- Refactored `jets_calibration.yaml` parameters to contain both MC and Data JES files 
- Refactored `base` workflow to apply JES on nominal and not only if JES variations are requested

Addressing issue #177

### CODE REVIEW

**Comment by andreypz** [comment]
I run with this branch and it works for me!
I also confirm that the Jet's scale is much improved in Data (only looked at 2023 ). I would say it can be merged.

One thing is not clear though is if JER smearing is applied to MC, or not. Looking at the pt(jj)/pt(ll) ratio, the MC is a bit narrower than Data, which suggests the the jet's pT are not smeared (enough).

dilep_dijet_ratio_2023_postBPix_baseline_2L2J_no_ctag

**Comment by valsdav** [comment]
Ok nice! I see that JER is included for Run3 MC in the configuration. 
If it is defined as part of the correction files it should be applied alongside the JEC. 
Maybe you can define another correction set without JER (https://github.com/PocketCoffea/PocketCoffea/blob/jec_nominal/pocket_coffea/parameters/jets_calibration.yaml#L215) in your custom parameters and see if we see a difference without the JER applied?

**Comment by valsdav** [comment]
I also noticed this warning when preparing the jet corrector maps:

```
Creating AK4PFPuppi jet calibrator for 2022_postEE
/t3home/dvalsecc/micromamba/envs/pocket-coffea/lib/python3.9/site-packages/coffea/lookup_tools/txt_converters.py:166: UserWarning: binning for file for Summer22EEPrompt22_JRV1_MC_PtResolution_AK4PFPuppi is malformed in variable JetEta
```

**Comment by andreypz** [comment]
I commented out the `MC_PtResolution_AK4PFPuppi.jr.txt.gz` and `MC_SF_AK4PFPuppi.jersf.txt.gz` files from the jecs config and rerun.
I do see an effect, here is a plot:
dilep_dijet_ratio_2023_postBPix_baseline_2L2J_no_ctag

The MC distribution does look a little bit narrower, but the difference is not much with respect to JER corrected plot I posted before...

I also get the Warnings about the JER correction files, but I have not checked 2022 plots yet.

But I think this PR itself is good to be merged. 
The issues need to be discussed with JETMET group (maybe after switching to correctionlib implementation).

**Comment by valsdav** [comment]
Ok! Merging now the technical PR. We will followup on the actual correction themselves. 

For the correctionlib implementation. We will discuss with central coffea to understand how to integrate correctionlib in the CorrectedJetFactory that we are using right now :+1:. We don't want an in-house solution for that.

**Pull request merged**
